# Generated by OpenQL 0.10.0 for program bernstein-vazirani
version 1.0

qubits 10


.bv_kernel
    h q[0]
    h q[1]
    h q[2]
    h q[3]
    h q[4]
    x q[5]
    h q[5]
    cnot q[0], q[5]
    cnot q[1], q[5]
    cnot q[2], q[5]
    cnot q[3], q[5]
    h q[0]
    measure q[0]
    h q[1]
    measure q[1]
    h q[2]
    measure q[2]
    h q[3]
    measure q[3]
    h q[4]
    measure q[4]
