# Generated by OpenQL 0.10.0 for program grovers-single
version 1.0

qubits 10


.grs_kernel
    h q[0]
    h q[1]
    cz q[0], q[1]
    h q[0]
    h q[1]
    z q[0]
    z q[1]
    cz q[0], q[1]
    h q[0]
    h q[1]
    measure q[0]
    measure q[1]
