# Generated by OpenQL 0.10.0 for program grovers-double
version 1.0

qubits 10


.grd_kernel
    h q[0]
    h q[1]
    h q[2]
    z q[0]
    cz q[0], q[1]
    cz q[0], q[2]
    h q[0]
    x q[0]
    h q[1]
    x q[1]
    h q[2]
    x q[2]
    h q[0]
    toffoli q[2], q[1], q[0]
    h q[0]
    x q[0]
    h q[0]
    x q[1]
    h q[1]
    x q[2]
    h q[2]
    measure q[0]
    measure q[1]
    measure q[2]
