# Generated by OpenQL 0.10.0 for program teleportation
version 1.0

qubits 10


.tp_kernel
    h q[0]
    h q[1]
    cnot q[1], q[2]
    cnot q[0], q[1]
    h q[0]
    cnot q[1], q[2]
    cz q[0], q[2]
    measure q[0]
    measure q[1]
    measure q[2]
